default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: app-garage_development

test:
  <<: *default
  database: app-garage_test

production:
  <<: *default
  database: app-garage_production
  username: app-garage
  password: <%= ENV['APP-GARAGE_DATABASE_PASSWORD'] %>
